export const MOCK_REGIONS = [
  {
    id: 'reg-13',
    region_name: 'Zone 2 - Dharampeth / Civil Lines (Nagpur)',
    latitude: 21.1458,
    longitude: 79.0720,
    population: 220000,
    infra_gap_score: 89.5,
    past_investment_amount: 1400000,
  },
  {
    id: 'reg-14',
    region_name: 'Zone 4 - Dhantoli / Sitabuldi (Nagpur)',
    latitude: 21.1420,
    longitude: 79.0850,
    population: 210000,
    infra_gap_score: 87.0,
    past_investment_amount: 1100000,
  },
  {
    id: 'reg-01',
    region_name: 'Ward 12 - Dharavi / Shahu Nagar',
    latitude: 19.0402,
    longitude: 72.8508,
    population: 850000,
    infra_gap_score: 92.4,
    past_investment_amount: 1850000,
  },
  {
    id: 'reg-02',
    region_name: 'Ward 9 - Kurla West / LBS Marg',
    latitude: 19.0688,
    longitude: 72.8797,
    population: 620000,
    infra_gap_score: 86.8,
    past_investment_amount: 2400000,
  },
  {
    id: 'reg-03',
    region_name: 'Ward 15 - Chembur North / Govandi',
    latitude: 19.0560,
    longitude: 72.9090,
    population: 540000,
    infra_gap_score: 81.5,
    past_investment_amount: 3100000,
  },
  {
    id: 'reg-04',
    region_name: 'Ward 8 - Andheri East / MIDC Industrial',
    latitude: 19.1176,
    longitude: 72.8631,
    population: 780000,
    infra_gap_score: 74.2,
    past_investment_amount: 5900000,
  },
  {
    id: 'reg-05',
    region_name: 'Ward 7 - Shivaji Nagar / Mankhurd',
    latitude: 19.0583,
    longitude: 72.9312,
    population: 490000,
    infra_gap_score: 89.1,
    past_investment_amount: 1420000,
  },
  {
    id: 'reg-06',
    region_name: 'Ward 4 - Bandra West / Hill Road',
    latitude: 19.0596,
    longitude: 72.8295,
    population: 320000,
    infra_gap_score: 61.3,
    past_investment_amount: 4800000,
  },
  {
    id: 'reg-07',
    region_name: 'Ward 1 - Colaba / Fort Financial District',
    latitude: 18.9220,
    longitude: 72.8347,
    population: 210000,
    infra_gap_score: 44.5,
    past_investment_amount: 8200000,
  },
  {
    id: 'reg-08',
    region_name: 'Ward 22 - Hinjewadi IT Corridor',
    latitude: 18.5913,
    longitude: 73.7389,
    population: 290000,
    infra_gap_score: 78.4,
    past_investment_amount: 3900000,
  },
  {
    id: 'reg-09',
    region_name: 'Ward 18 - Kothrud / Karve Road',
    latitude: 18.5074,
    longitude: 73.8077,
    population: 340000,
    infra_gap_score: 55.2,
    past_investment_amount: 2700000,
  },
  {
    id: 'reg-10',
    region_name: 'Ward 3 - Whitefield Tech Zone',
    latitude: 12.9698,
    longitude: 77.7500,
    population: 310000,
    infra_gap_score: 72.0,
    past_investment_amount: 4200000,
  },
  {
    id: 'reg-11',
    region_name: 'Ward 5 - Indiranagar / Halasuru',
    latitude: 12.9784,
    longitude: 77.6408,
    population: 240000,
    infra_gap_score: 52.0,
    past_investment_amount: 3600000,
  },
  {
    id: 'reg-12',
    region_name: 'Ward 11 - Old City / Charminar Heritage',
    latitude: 17.3616,
    longitude: 78.4747,
    population: 380000,
    infra_gap_score: 81.0,
    past_investment_amount: 1900000,
  },
  {
    id: 'reg-15',
    region_name: 'Zone 1 - Laxmi Nagar / Bajaj Nagar (Nagpur)',
    latitude: 21.1250,
    longitude: 79.0650,
    population: 245000,
    infra_gap_score: 68.5,
    past_investment_amount: 1650000,
  },
  {
    id: 'reg-16',
    region_name: 'Zone 3 - Hanuman Nagar / Medical Square (Nagpur)',
    latitude: 21.1180,
    longitude: 79.0950,
    population: 260000,
    infra_gap_score: 78.0,
    past_investment_amount: 950000,
  },
  {
    id: 'reg-17',
    region_name: 'Zone 6 - Gandhibagh / Itwari / Old City (Nagpur)',
    latitude: 21.1550,
    longitude: 79.1100,
    population: 310000,
    infra_gap_score: 85.5,
    past_investment_amount: 720000,
  },
  {
    id: 'reg-18',
    region_name: 'Zone 10 - Mangalwari / Sadar (Nagpur)',
    latitude: 21.1650,
    longitude: 79.0780,
    population: 250000,
    infra_gap_score: 65.0,
    past_investment_amount: 1800000,
  },
  {
    id: 'reg-19',
    region_name: 'Zone 9 - Ashi Nagar / Jaripatka (Nagpur)',
    latitude: 21.1850,
    longitude: 79.0980,
    population: 290000,
    infra_gap_score: 88.0,
    past_investment_amount: 850000,
  },
  {
    id: 'reg-20',
    region_name: 'MIHAN / Butibori Industrial Zone (Nagpur)',
    latitude: 21.0350,
    longitude: 79.0250,
    population: 180000,
    infra_gap_score: 81.0,
    past_investment_amount: 2100000,
  },
];

export const MOCK_SUBMISSIONS = [
  {
    id: 'sub-ngp-01',
    raw_input_type: 'voice',
    raw_text: 'Dharampeth main road par 100mm drinking water feeder line burst ho gayi hai, do din se pure area me paani nahi aa raha.',
    language_detected: 'Hindi',
    translated_text: 'A 100mm drinking water feeder pipeline has burst on Dharampeth main road, completely disrupting drinking water supply for two days.',
    category: 'water',
    latitude: 21.1458,
    longitude: 79.0720,
    region_name: 'Zone 2 - Dharampeth / Civil Lines (Nagpur)',
    urgency_score: 96.0,
    status: 'prioritized',
    created_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    id: 'sub-ngp-02',
    raw_input_type: 'text',
    raw_text: 'Sitabuldi main market entrance road crater and exposed high-voltage cables causing severe road block and electrocution hazard.',
    language_detected: 'English',
    translated_text: 'Sitabuldi main market entrance road crater and exposed high-voltage cables causing severe road block and electrocution hazard.',
    category: 'roads',
    latitude: 21.1420,
    longitude: 79.0850,
    region_name: 'Zone 4 - Dhantoli / Sitabuldi (Nagpur)',
    urgency_score: 93.5,
    status: 'prioritized',
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'sub-ngp-03',
    raw_input_type: 'voice',
    raw_text: 'Transformer spark jhalay, Medical Square jawal purya line madhe light nahi ahe, emergency patient sathi problem ahe.',
    language_detected: 'Marathi',
    translated_text: 'Transformer sparked near Medical Square, high voltage power loss affecting hospital ICU perimeter.',
    category: 'electricity',
    latitude: 21.1180,
    longitude: 79.0950,
    region_name: 'Zone 3 - Hanuman Nagar / Medical Square (Nagpur)',
    urgency_score: 92.0,
    status: 'prioritized',
    created_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    id: 'sub-ngp-04',
    raw_input_type: 'text',
    raw_text: 'MIHAN approach road open drainage overflow causing heavy vehicle skidding and severe sanitation issues.',
    language_detected: 'English',
    translated_text: 'MIHAN approach road open drainage overflow causing heavy vehicle skidding and severe sanitation issues.',
    category: 'sanitation',
    latitude: 21.0350,
    longitude: 79.0250,
    region_name: 'MIHAN / Butibori Industrial Zone (Nagpur)',
    urgency_score: 86.5,
    status: 'prioritized',
    created_at: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
  },
  {
    id: 'sub-ngp-05',
    raw_input_type: 'text',
    raw_text: 'Laxmi Nagar 8-inch water pipe rupture flooding residential basements.',
    language_detected: 'English',
    translated_text: 'Laxmi Nagar 8-inch water pipe rupture flooding residential basements.',
    category: 'water',
    latitude: 21.1250,
    longitude: 79.0650,
    region_name: 'Zone 1 - Laxmi Nagar / Bajaj Nagar (Nagpur)',
    urgency_score: 84.0,
    status: 'prioritized',
    created_at: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
  },
];

export const MOCK_PRIORITIES = [
  {
    id: 'p-01',
    final_priority_rank: 1,
    region_name: 'Zone 2 - Dharampeth / Civil Lines (Nagpur)',
    category: 'water',
    submission_count: 8,
    avg_urgency: 96.0,
    recommended_action: 'Deploy emergency pipeline repair crew and install secondary 50,000L potable distribution manifold in Zone 2 - Dharampeth (Nagpur).',
    generated_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'p-02',
    final_priority_rank: 2,
    region_name: 'Zone 4 - Dhantoli / Sitabuldi (Nagpur)',
    category: 'roads',
    submission_count: 6,
    avg_urgency: 93.5,
    recommended_action: 'Deploy rapid cold-mix asphalt concrete reinforcement crew to repair arterial craters near Sitabuldi station.',
    generated_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'p-03',
    final_priority_rank: 3,
    region_name: 'Zone 3 - Hanuman Nagar / Medical Square (Nagpur)',
    category: 'electricity',
    submission_count: 5,
    avg_urgency: 92.0,
    recommended_action: 'Isolate malfunctioning step-down transformer and replace leaking oil gaskets outside Medical Square.',
    generated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'p-04',
    final_priority_rank: 4,
    region_name: 'MIHAN / Butibori Industrial Zone (Nagpur)',
    category: 'sanitation',
    submission_count: 4,
    avg_urgency: 86.5,
    recommended_action: 'Dispatch dedicated mechanical garbage compactor and clear arterial drainage overflow in MIHAN industrial zone.',
    generated_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'p-05',
    final_priority_rank: 5,
    region_name: 'Zone 1 - Laxmi Nagar / Bajaj Nagar (Nagpur)',
    category: 'water',
    submission_count: 3,
    avg_urgency: 84.0,
    recommended_action: 'Repair secondary distribution line and flush contaminated branch main in Laxmi Nagar.',
    generated_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
];
