export const MOCK_REGIONS = [
  { id: '1', region_name: 'East Ward - Sector 4', latitude: 21.1458, longitude: 79.0882, population: 145000, infra_gap_score: 84.5, past_investment_amount: 1200000 },
  { id: '2', region_name: 'Industrial Zone North', latitude: 21.1620, longitude: 79.0710, population: 98000, infra_gap_score: 91.2, past_investment_amount: 450000 },
  { id: '3', region_name: 'Metro Corridor South', latitude: 21.1210, longitude: 79.0650, population: 210000, infra_gap_score: 62.0, past_investment_amount: 3400000 },
  { id: '4', region_name: 'Old City Settlement', latitude: 21.1510, longitude: 79.1120, population: 180000, infra_gap_score: 89.0, past_investment_amount: 890000 },
  { id: '5', region_name: 'Lakeside Urban Colony', latitude: 21.1380, longitude: 79.0430, population: 76000, infra_gap_score: 41.5, past_investment_amount: 2100000 },
  { id: '6', region_name: 'Suburban Tech Park', latitude: 21.1090, longitude: 79.0150, population: 65000, infra_gap_score: 35.0, past_investment_amount: 5200000 },
  { id: '7', region_name: 'Greenfield Extension Block', latitude: 21.1780, longitude: 79.0950, population: 52000, infra_gap_score: 77.8, past_investment_amount: 600000 },
];

export const MOCK_SUBMISSIONS = [
  {
    id: 'sub-01',
    raw_input_type: 'voice',
    raw_text: 'Yahan 4 din se drinking water supply band hai, tankers bhi nahi aa rahe.',
    language_detected: 'Hindi',
    translated_text: 'Drinking water supply has been shut down for 4 days here, even water tankers are not arriving.',
    category: 'water',
    latitude: 21.1458,
    longitude: 79.0882,
    region_name: 'East Ward - Sector 4',
    urgency_score: 92.4,
    status: 'prioritized',
    created_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    id: 'sub-02',
    raw_input_type: 'text',
    raw_text: 'Main road outside industrial cluster has multiple severe potholes causing freight vehicle accidents.',
    language_detected: 'English',
    translated_text: 'Main road outside industrial cluster has multiple severe potholes causing freight vehicle accidents.',
    category: 'roads',
    latitude: 21.1620,
    longitude: 79.0710,
    region_name: 'Industrial Zone North',
    urgency_score: 88.7,
    status: 'prioritized',
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'sub-03',
    raw_input_type: 'voice',
    raw_text: 'Transformer blast jhalay, purya basti madhe light nahi ahe 24 taasapasun.',
    language_detected: 'Marathi',
    translated_text: 'Transformer blast occurred, the entire settlement is without electricity for over 24 hours.',
    category: 'electricity',
    latitude: 21.1510,
    longitude: 79.1120,
    region_name: 'Old City Settlement',
    urgency_score: 95.1,
    status: 'prioritized',
    created_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    id: 'sub-04',
    raw_input_type: 'text',
    raw_text: 'Open drainage overflow during monsoon clogging primary school entrance.',
    language_detected: 'English',
    translated_text: 'Open drainage overflow during monsoon clogging primary school entrance.',
    category: 'sanitation',
    latitude: 21.1458,
    longitude: 79.0882,
    region_name: 'East Ward - Sector 4',
    urgency_score: 83.2,
    status: 'reviewed',
    created_at: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
  },
  {
    id: 'sub-05',
    raw_input_type: 'text',
    raw_text: 'Streetlights on Metro feeder road have been flickering and completely dark for 3 weeks.',
    language_detected: 'English',
    translated_text: 'Streetlights on Metro feeder road have been flickering and completely dark for 3 weeks.',
    category: 'electricity',
    latitude: 21.1210,
    longitude: 79.0650,
    region_name: 'Metro Corridor South',
    urgency_score: 61.5,
    status: 'new',
    created_at: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
  },
];

export const MOCK_PRIORITIES = [
  {
    id: 'p-01',
    final_priority_rank: 1,
    region_name: 'Old City Settlement',
    category: 'electricity',
    submission_count: 28,
    avg_urgency: 94.8,
    recommended_action: 'Dispatch emergency substation repair team and deploy mobile backup generators to ward clinic.',
    generated_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'p-02',
    final_priority_rank: 2,
    region_name: 'East Ward - Sector 4',
    category: 'water',
    submission_count: 42,
    avg_urgency: 91.6,
    recommended_action: 'Route 6 municipal tankers immediately and isolate broken feeder main valve at junction 12.',
    generated_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'p-03',
    final_priority_rank: 3,
    region_name: 'Industrial Zone North',
    category: 'roads',
    submission_count: 36,
    avg_urgency: 87.2,
    recommended_action: 'Deploy emergency asphalt cold-mix patch crew and divert heavy logistics traffic via bypass.',
    generated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'p-04',
    final_priority_rank: 4,
    region_name: 'East Ward - Sector 4',
    category: 'sanitation',
    submission_count: 19,
    avg_urgency: 81.0,
    recommended_action: 'Deploy high-velocity sewer suction vehicle to clear school drainage culvert.',
    generated_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'p-05',
    final_priority_rank: 5,
    region_name: 'Greenfield Extension Block',
    category: 'water',
    submission_count: 15,
    avg_urgency: 76.4,
    recommended_action: 'Commission temporary pipeline interconnection from northern reservoir.',
    generated_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
];
