export const MOCK_REGIONS = [
  {
    id: 'reg-01',
    region_name: 'Ward 12 - Dharavi / Shahu Nagar',
    latitude: 19.0402,
    longitude: 72.8508,
    population: 850000,
    infra_gap_score: 92.4,
    past_investment_amount: 1850000,
  },
  {
    id: 'reg-02',
    region_name: 'Ward 9 - Kurla West / LBS Marg',
    latitude: 19.0688,
    longitude: 72.8797,
    population: 620000,
    infra_gap_score: 86.8,
    past_investment_amount: 2400000,
  },
  {
    id: 'reg-03',
    region_name: 'Ward 15 - Chembur North / Govandi',
    latitude: 19.0560,
    longitude: 72.9090,
    population: 540000,
    infra_gap_score: 81.5,
    past_investment_amount: 3100000,
  },
  {
    id: 'reg-04',
    region_name: 'Ward 8 - Andheri East / MIDC Industrial',
    latitude: 19.1176,
    longitude: 72.8631,
    population: 780000,
    infra_gap_score: 74.2,
    past_investment_amount: 5900000,
  },
  {
    id: 'reg-05',
    region_name: 'Ward 7 - Shivaji Nagar / Mankhurd',
    latitude: 19.0583,
    longitude: 72.9312,
    population: 490000,
    infra_gap_score: 89.1,
    past_investment_amount: 1420000,
  },
  {
    id: 'reg-06',
    region_name: 'Ward 4 - Bandra West / Hill Road',
    latitude: 19.0596,
    longitude: 72.8295,
    population: 320000,
    infra_gap_score: 61.3,
    past_investment_amount: 4800000,
  },
  {
    id: 'reg-07',
    region_name: 'Ward 1 - Colaba / Fort Financial District',
    latitude: 18.9220,
    longitude: 72.8347,
    population: 210000,
    infra_gap_score: 44.5,
    past_investment_amount: 8200000,
  },
  {
    id: 'reg-08',
    region_name: 'Ward 22 - Hinjewadi IT Corridor',
    latitude: 18.5913,
    longitude: 73.7389,
    population: 290000,
    infra_gap_score: 78.4,
    past_investment_amount: 3900000,
  },
  {
    id: 'reg-09',
    region_name: 'Ward 18 - Kothrud / Karve Road',
    latitude: 18.5074,
    longitude: 73.8077,
    population: 340000,
    infra_gap_score: 55.2,
    past_investment_amount: 2700000,
  },
  {
    id: 'reg-10',
    region_name: 'Ward 3 - Whitefield Tech Zone',
    latitude: 12.9698,
    longitude: 77.7500,
    population: 310000,
    infra_gap_score: 72.0,
    past_investment_amount: 4200000,
  },
  {
    id: 'reg-11',
    region_name: 'Ward 5 - Indiranagar / Halasuru',
    latitude: 12.9784,
    longitude: 77.6408,
    population: 240000,
    infra_gap_score: 52.0,
    past_investment_amount: 3600000,
  },
  {
    id: 'reg-12',
    region_name: 'Ward 11 - Old City / Charminar Heritage',
    latitude: 17.3616,
    longitude: 78.4747,
    population: 380000,
    infra_gap_score: 81.0,
    past_investment_amount: 1900000,
  },
];

export const MOCK_SUBMISSIONS = [
  {
    id: 'sub-01',
    raw_input_type: 'voice',
    raw_text: 'Hamare chawl me 90 feet road par main paani pipe phat gaya hai, 3 din se peene ka paani nahi aa raha.',
    language_detected: 'Hindi',
    translated_text: 'Drinking water supply pipeline burst on 90 Feet Road, whole settlement has zero drinking water for 3 days.',
    category: 'water',
    latitude: 19.0418,
    longitude: 72.8524,
    region_name: 'Ward 12 - Dharavi / Shahu Nagar',
    urgency_score: 94.5,
    status: 'prioritized',
    created_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    id: 'sub-02',
    raw_input_type: 'text',
    raw_text: 'LBS Marg bridge approach has massive 2-foot sinkhole after water main collapse. Buses and ambulances getting stuck.',
    language_detected: 'English',
    translated_text: 'LBS Marg bridge approach has massive 2-foot sinkhole after water main collapse. Buses and ambulances getting stuck.',
    category: 'roads',
    latitude: 19.0712,
    longitude: 72.8812,
    region_name: 'Ward 9 - Kurla West / LBS Marg',
    urgency_score: 88.7,
    status: 'prioritized',
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'sub-03',
    raw_input_type: 'voice',
    raw_text: 'Kurla station jawal motha khadda padla ahe, ambulance adakli hoti kal ratri.',
    language_detected: 'Marathi',
    translated_text: 'Large sinkhole formed near Kurla station, ambulance was trapped last night.',
    category: 'roads',
    latitude: 19.0688,
    longitude: 72.8797,
    region_name: 'Ward 9 - Kurla West / LBS Marg',
    urgency_score: 92.1,
    status: 'prioritized',
    created_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    id: 'sub-04',
    raw_input_type: 'text',
    raw_text: 'Garbage compactor has not visited Baiganwadi sector 4 in 11 days. Piles spilling onto road blocking traffic.',
    language_detected: 'English',
    translated_text: 'Garbage compactor has not visited Baiganwadi sector 4 in 11 days. Piles spilling onto road blocking traffic.',
    category: 'sanitation',
    latitude: 19.0601,
    longitude: 72.9345,
    region_name: 'Ward 7 - Shivaji Nagar / Mankhurd',
    urgency_score: 86.3,
    status: 'prioritized',
    created_at: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
  },
  {
    id: 'sub-05',
    raw_input_type: 'text',
    raw_text: 'High voltage transformer spark and oil leakage outside school gate on Hill Road.',
    language_detected: 'English',
    translated_text: 'High voltage transformer spark and oil leakage outside school gate on Hill Road.',
    category: 'electricity',
    latitude: 19.0560,
    longitude: 72.8290,
    region_name: 'Ward 4 - Bandra West / Hill Road',
    urgency_score: 89.4,
    status: 'prioritized',
    created_at: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
  },
];

export const MOCK_PRIORITIES = [
  {
    id: 'p-01',
    final_priority_rank: 1,
    region_name: 'Ward 12 - Dharavi / Shahu Nagar',
    category: 'water',
    submission_count: 8,
    avg_urgency: 93.4,
    recommended_action: 'Deploy emergency pipeline repair crew and install secondary 50,000L potable distribution manifold in Ward 12.',
    generated_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'p-02',
    final_priority_rank: 2,
    region_name: 'Ward 9 - Kurla West / LBS Marg',
    category: 'roads',
    submission_count: 6,
    avg_urgency: 89.2,
    recommended_action: 'Deploy rapid cold-mix asphalt concrete reinforcement crew to repair arterial sinkholes near Kurla station.',
    generated_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'p-03',
    final_priority_rank: 3,
    region_name: 'Ward 7 - Shivaji Nagar / Mankhurd',
    category: 'sanitation',
    submission_count: 5,
    avg_urgency: 86.5,
    recommended_action: 'Dispatch dedicated mechanical garbage compactor and clear arterial drainage overflow in Mankhurd.',
    generated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'p-04',
    final_priority_rank: 4,
    region_name: 'Ward 4 - Bandra West / Hill Road',
    category: 'electricity',
    submission_count: 4,
    avg_urgency: 84.0,
    recommended_action: 'Isolate malfunctioning step-down transformer and replace leaking oil gaskets outside school zone.',
    generated_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'p-05',
    final_priority_rank: 5,
    region_name: 'Ward 15 - Chembur North / Govandi',
    category: 'water',
    submission_count: 3,
    avg_urgency: 80.5,
    recommended_action: 'Repair secondary distribution line and flush contaminated branch main.',
    generated_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
];
